# Generated by Django 5.1 on 2024-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_company_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
